### PR TITLE
Feat/water obstacle Ball resets on contact with a "water" typed polyline

### PR DESCRIPTION
**Pull request by Brogzybro**

### CODE REVIEW

**Comment by Brogzybro** [comment]
maybe having the whole water tile as an object, and not just a drawn polyline.

**Review by Jonas-C — APPROVED** [review]
I think this is good. Maybe we should consider abstracting WaterComponent to allow for having stuff like LavaComponent, SpikeComponent etc under the same umbrella?

**Review by Trulsmatias — APPROVED** [review]
Looks good :)

**Comment by Brogzybro** [comment]
workes with mp

**Pull request merged**
